analysis:
  type: "full"
trimming:
  read1: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
  read2: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
  source: "TruSeq SingleIndex"
mapping:
  gtf: "http://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/genes/mm10.refGene.gtf.gz"
  fasta: "https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/chromFa.tar.gz"
  read_length: 76
  index_genome: "true"
  genes: "https://sourceforge.net/projects/rseqc/files/BED/Mouse_Mus_musculus/mm10_RefSeq.bed.gz/download"
counting:
  type: "Antisense-Stranded"
